--- 
title: "provincial NSYT production process and assessment"
author: "Shuyan Jiang, Kelly Izzard, Yingbing Chen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
---

# Prerequisites

This is the documentation of how provincial natural stand yield table (NSYT) was generated and the assessments of the product.

```{r eval=FALSE, echo=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")

##to render the book
# 
# You can render the HTML version of this example book without changing anything:
# 
# 1. Find the **Build** pane in the RStudio IDE, and
# 
# 1. Click on **Build Book**, then select your output format, or select "All formats" if you'd like to use multiple formats from the same book source files.
# 
# Or build the book from the R console:
# 
# bookdown::render_book()
# 
# To render this example to PDF as a `bookdown::pdf_book`, you'll need to install XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.org/tinytex/>.
## Preview book

# As you work, you may start a local server to live preview this HTML book. This preview will update as you edit the book when you save individual .Rmd files. You can start the server in a work session by using the RStudio add-in "Preview book", or from the R console:
# 
# bookdown::serve_book()
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
